theme: jekyll-theme-minimal
title: > analisaR
description: Análise e visualização de dados socioambientais e de biodiversidade
logo: "/analisaR_logomarca_final_final_final_final_final.png"
show_downloads: false
