theme: jekyll-theme-minimal
title: analisaR 
description: Análise e visualização de dados socioambientais e de biodiversidade (CNPJ 42.948.481.0001/01)
logo: "analisaR_DNA_USP.png"
show_downloads: false
